# train_model.py
"""
Train a classifier on pairwise features generated by prepare_pairs.py.

Inputs:
  pairs_train.pkl
Outputs:
  model_lr.joblib
  model_rf.joblib
  scaler.joblib
"""

import pandas as pd
import numpy as np
import joblib
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, roc_auc_score, accuracy_score

RND_SEED = 42
PAIRS_PKL = "pairs_train.pkl"
MODEL_OUT = "model.joblib"
SCALER_OUT = "scaler.joblib"

def load_pairs():
    df = pd.read_pickle(PAIRS_PKL)
    return df

def prepare_xy(df):
    X = df[[
        'cosine_text','jaccard_desc','color_match','brand_match',
        'location_match','user_match','time_diff_hours','len_diff','name_match'
    ]].fillna(0.0).astype(float)
    y = df['label'].astype(int)
    return X, y

def main():
    df = load_pairs()
    X, y = prepare_xy(df)
    X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.20, stratify=y, random_state=RND_SEED)

    # scale numeric columns
    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train)
    X_val_scaled = scaler.transform(X_val)
    joblib.dump(scaler, SCALER_OUT)

    # logistic regression baseline
    print("Training Logistic Regression...")
    clf = LogisticRegression(max_iter=2000, class_weight='balanced', random_state=RND_SEED)
    clf.fit(X_train_scaled, y_train)
    y_pred = clf.predict(X_val_scaled)
    y_proba = clf.predict_proba(X_val_scaled)[:,1]

    print("Validation classification report (Logistic Regression):")
    print(classification_report(y_val, y_pred))
    print("ROC AUC:", roc_auc_score(y_val, y_proba))

    # Optionally train RandomForest for better ranking performance
    print("Training RandomForest for comparison (may take longer)...")
    rf = RandomForestClassifier(n_estimators=200, max_depth=12, class_weight='balanced', random_state=RND_SEED, n_jobs=-1)
    rf.fit(X_train, y_train)
    y_pred_rf = rf.predict(X_val)
    y_proba_rf = rf.predict_proba(X_val)[:,1]
    print("RandomForest classification report:")
    print(classification_report(y_val, y_pred_rf))
    print("ROC AUC (RF):", roc_auc_score(y_val, y_proba_rf))

    # Save the chosen model (you can pick rf or clf)
    # We'll save both: model_lr.joblib and model_rf.joblib
    joblib.dump(clf, "model_lr.joblib")
    joblib.dump(rf, "model_rf.joblib")
    print("Saved model_lr.joblib and model_rf.joblib to current directory")

if __name__ == "__main__":
    main()
